Library/Library.Web/Controllers/UserController.cs
using Library.API.Client;
using Library.Common;
using Library.Services.Contracts;
using Library.Services.DTOs;
using Library.Web.Models;
using Library.Web.Models.Mappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Library.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _us;
        private readonly CloudinaryClient _cloudinary;
        public UserController(IUserService us, CloudinaryClient cloudinary)
        {
            _us = us;
            _cloudinary = cloudinary;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Profile()
        {
            var email = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;

            var user = await _us.GetUserByEmailOrIdAsync(email);

            var model = user.GetDTO();

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(SettingsViewModel model)
        {
            var email = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;

            var user = await _us.GetUserByEmailOrIdAsync(email);

            if(model.ProfilePicture != null)
            {
                var url = _cloudinary.UploadProfilePhotoAsync(model.ProfilePicture);

                await _us.UpdateProfilePicture(email, url.Result.Url.ToString());
            }

            var modelToDTO = model.GetDTO();

            if (modelToDTO != null)
            {
                await _us.UpdateAsync(email, modelToDTO);
                //TODO Some notification if its succesfull or not?
                if(user.Password == model.Password)
                {
                    await _us.UpdatePasswordAsync(email, model.NewPassword);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Index(string part = "@", int? currentpage = 1)
        {
            ViewData["TotalPages"] = await _us.UsersCountAsync() / 10;
            ViewData["CurrentFilter"] = part;

            if (currentpage.HasValue)
            {
                if (currentpage.Value > 0) currentpage--; else { currentpage = 0; }
            }
            var users = await _us.FilterUsersAsync(currentpage ?? 0, part);

            ViewData["CurrentPage"] = currentpage + 1;
            return View(users);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Details(long id)
        {
            var user = await _us.GetUserByEmailOrIdAsync(id.ToString());

            var model = user.GetDTO();

            return View(model);
        }
    }
}

Library/Library.Web/Views/Shared/_AdminLayout.cshtml
@using Library.Common
@{
    var role = Context.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role)?.Value;
}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>@ViewData["Title"] - UniBIT Library</title>
  <link rel="icon" href="http://localhost:5001/favicon.ico"/>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="~/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="~/css/responsive.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="sub_page">
  <div class="hero_area">
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" asp-controller="Home" asp-action="Index">
              <h3>
                  Unibit
              </h3>
              <span>
                  library
              </span>
           </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
            <ul class="navbar-nav  ml-auto">
              <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Homepage</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="User" asp-action="Index">Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Book" asp-action="Index">Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Author" asp-action="Index">Authors</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="PublishHouse" asp-action="Index">Publish Houses</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Loan" asp-action="GetAll">Loans</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>
  @RenderBody()
  <!-- info section -->
  <section class="info_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_menu">
            <h5>
              QUICK LINKS
            </h5>
            <ul class="navbar-nav  ">
              <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Homepage</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="User" asp-action="Options">Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Book" asp-action="Options">Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Author" asp-action="Options">Authors</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="PublishHouse" asp-action="Options">Publish Houses</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-5 offset-md-1">
          <div class="info_news">
            <h5>
              FOR ANY QUERY, PLEASE WRITE TO US
            </h5>
            <div class="info_contact">
              <a>
                Location
              </a>
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d751147.8180823668!2d23.387706228219223!3d42.657728094510524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40aa868a6c82fc05%3A0xed9dd2cc56a95d15!2z0KPQvdC40LLQtdGA0YHQuNGC0LXRgiDQv9C-INCx0LjQsdC70LjQvtGC0LXQutC-0LfQvdCw0L3QuNC1INC4INC40L3RhNC-0YDQvNCw0YbQuNC-0L3QvdC4INGC0LXRhdC90L7Qu9C-0LPQuNC4!5e0!3m2!1sbg!2sbg!4v1644491704432!5m2!1sbg!2sbg" width="400" height="250" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
              <a>
                devvpurposeemail@gmail.com
              </a>
              <a>
                Call : +01 1234567890
              </a>
            </div>
            <form asp-controller="Home" asp-action ="Contact">
              <button>
                Contact form
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <p>
      &copy; 2022 All Rights Reserved By 
    </p>
  </footer> 
  <!-- footer section -->
    <script type="text/javascript" src="~/js~/js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="~/js~/js/bootstrap.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Library/Library.Web/Views/Shared/_Layout.cshtml
@using Library.Common
@{
    var role = Context.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role)?.Value;
}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>@ViewData["Title"] - UniBIT Library</title>
  <link rel="icon" href="http://localhost:5001/favicon.ico"/>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="~/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="~/css/responsive.css" rel="stylesheet" />
</head>
<body class="sub_page">
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" asp-controller="Home" asp-action="Index">
              <h3>
                  Unibit
              </h3>
              <span>
                  library
              </span>
           </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
            <ul class="navbar-nav  ml-auto">
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller ="Books" asp-action="Index"> Books </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller ="Home" asp-action= "Contact">Contact us</a>
              </li>
              @if(role == null)
              {
                <li class="nav-item">
                <a class="nav-link" asp-controller = "Auth" asp-action = "Login">Login</a>
                </li>
              }
              @if(role != null)
              {
                <li class="nav-item">
                <a class="nav-link" asp-controller = "User" asp-action = "Profile">Profile</a>
                </li>
                if(role != GlobalConstants.NotConfirmedRoleName)
                {
                    <li class="nav-item">
                    <a class="nav-link" asp-controller = "Loan" asp-action = "Index">My loans</a>
                    </li>
                }
                if(role == GlobalConstants.AdministratorRoleName)
                {
                    <li class="nav-item">
                    <a class="nav-link" asp-controller = "Admin" asp-action = "Index">Admin</a>
                    </li>
                }
                <li class="nav-item">
                <a class="nav-link" asp-controller = "Auth" asp-action = "Logout">Logout</a>
                </li>
              }
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>
  @RenderBody()
  <!-- info section -->
  <section class="info_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_menu">
            <h5>
              QUICK LINKS
            </h5>
            <ul class="navbar-nav  ">
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller ="Books" asp-action="Index"> Books </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller ="Home" asp-action= "Contact">Contact us</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-5 offset-md-1">
          <div class="info_news">
            <h5>
              FOR ANY QUERY, PLEASE WRITE TO US
            </h5>
            <div class="info_contact">
              <a>
                Location
              </a>
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d751147.8180823668!2d23.387706228219223!3d42.657728094510524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40aa868a6c82fc05%3A0xed9dd2cc56a95d15!2z0KPQvdC40LLQtdGA0YHQuNGC0LXRgiDQv9C-INCx0LjQsdC70LjQvtGC0LXQutC-0LfQvdCw0L3QuNC1INC4INC40L3RhNC-0YDQvNCw0YbQuNC-0L3QvdC4INGC0LXRhdC90L7Qu9C-0LPQuNC4!5e0!3m2!1sbg!2sbg!4v1644491704432!5m2!1sbg!2sbg" width="400" height="250" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
              <a>
                devvpurposeemail@gmail.com
              </a>
              <a>
                Call : +01 1234567890
              </a>
            </div>
            <form asp-controller="Home" asp-action ="Contact">
              <button>
                Contact form
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <p>
      &copy; 2022 All Rights Reserved By 
    </p>
  </footer> 
  <!-- footer section -->
    <script type="text/javascript" src="~/js~/js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="~/js~/js/bootstrap.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>